plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.140'
}

version = mod_version
group = mod_group_id

base {
    archivesName = "createaeronauticscurios-neoforge-${minecraft_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
    }

    mods {
        "${mod_id}" {
            sourceSet project.sourceSets.main
        }
    }
}

repositories {
    mavenLocal()
    maven {
        url = "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven { url = "https://maven.blamejared.com" } // JEI, Vazkii's Mods
    maven {url = "https://maven.theillusivec4.top/"} // Curios
    maven { url = "https://maven.createmod.net" }
    maven { url = "https://maven.ithundxr.dev/snapshots" }
    maven { url = "https://maven.tterrag.com/" }
    maven { url = "https://maven.ryanhcode.dev/releases" } //Aeronautics
}

dependencies {
    compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"
    runtimeOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}"

    implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    implementation("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    implementation("com.tterrag.registrate:Registrate:${registrate_version}")

    implementation("dev.ryanhcode.sable:sable-neoforge-1.21.1:2.0.3") {transitive = false}
    implementation("dev.eriksonn.aeronautics:aeronautics-neoforge-1.21.1:1.3.0")
    implementation("dev.simulated_team.simulated:simulated-neoforge-1.21.1:1.3.0")

    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
    runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")

//    implementation "curse.maven:gregtechceu-modern-890405:6766269"

}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}