modLoader="javafml"
loaderVersion="[2,)"
license="All rights reserved"
mixins=[{config="aeronautics_curios_compat.mixins.json"}]

[[mods]]
modId="aeronautics_curios_compat"
version="2.0"
displayName="Create Aeronautics Curios Compat"
authors="titammods"
description="Adds Curios slot and rendering support to the Create Aeronautics Aviator Goggles, and remote LinkedTypewriter usage via Curios slot."

[[dependencies.aeronautics_curios_compat]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.aeronautics_curios_compat]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.aeronautics_curios_compat]]
modId="curios"
type="required"
versionRange="[9.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.aeronautics_curios_compat]]
modId="create"
type="required"
versionRange="*"
ordering="AFTER"
side="BOTH"

[[dependencies.aeronautics_curios_compat]]
modId="aeronautics"
type="required"
versionRange="*"
ordering="AFTER"
side="BOTH"

[[dependencies.aeronautics_curios_compat]]
modId="simulated"
type="required"
versionRange="*"
ordering="AFTER"
side="BOTH"